### ISSUE TITLE
Route annotation could be inherited from a extended class already annotated

### ISSUE THREAD

**Issue by sorenmalling** [wbsply/route-annotation#3]
Given a class like this

```
#[Route('api')]
abstract class ApiController extends ActionController {}
```

And a implemented controller/endpoint like this
```
#[Route('contacts')
class ContactsController extends ApiController {}
```

Will prefix the `contacts` controller with `api` - giving nice `api` prefix as routes base

**Comment by mhsdesign** [comment]
sorry but no i dont like inheritance that much 😂 becomes hard to guess

**Comment by PRGfx** [comment]
I think the idea of this package is to see the routing configuration where the code is and inheritance makes it difficult to actually see where the eventually resolved values are coming from. Maybe it would be better if the inherited values are more explicit, maybe with an argument on the annotation or something like `<parentRoutes>/...`, however this feels less intuitive than the subroutes imo.

**Comment by bwaidelich** [comment]
I agree to the comments and would (personally) prefer

```php
#[Route(uriPattern: 'api/contacts')
class ContactsController extends ApiController {}
```

**Comment by sorenmalling** [comment]
> I think the idea of this package is to see the routing configuration where the code is

@PRGfx Damn good point! <3
